package main

var Locations = map[string]Location{
	"surface": {
		Name: "🌳 Surface",
		LootTable: map[string]float64{
			"wood":  0.6,
			"stone": 0.4,
		},
		EncounterChance: 0.1,
		EncounterTable: []Monster{
			{Name: "🟢 Slime", Health: 20, Damage: 5, LootTable: map[string]float64{"gel": 1.0}},
		},
		RequiredLevel: 1,
		Descriptions: []string{
			"The sun shines warmly through the leaves as you gather supplies.",
			"A gentle breeze carries the scent of pine and fresh earth.",
			"Birds chirp overhead while you work on the grassy plains.",
			"You find a sturdy tree and begin harvesting its timber.",
		},
	},
	"cave": {
		Name: "🕳️ Cave",
		LootTable: map[string]float64{
			"iron": 0.5,
			"coal": 0.5,
		},
		EncounterChance: 0.2,
		EncounterTable: []Monster{
			{Name: "🧟 Zombie", Health: 40, Damage: 10, LootTable: map[string]float64{"rotten_flesh": 1.0}},
			{Name: "🕷️ Spider", Health: 30, Damage: 12, LootTable: map[string]float64{"string": 1.0}},
		},
		RequiredLevel: 3,
		RequiredItem:  "stone_pickaxe",
		Descriptions: []string{
			"Water droplets echo in the damp silence of the cavern.",
			"The air grows cool and musty as you strike the rocky walls.",
			"Your torch light flickers against a vein of dark coal.",
			"The sound of your pickaxe rings out through the dark tunnels.",
		},
	},
	"abyss": {
		Name: "🌑 Abyss",
		LootTable: map[string]float64{
			"gold":           0.5,
			"diamond":        0.3,
			"abyss_crystal": 0.2,
		},
		EncounterChance: 0.3,
		EncounterTable: []Monster{
			{Name: "👻 Shadow Stalker", Health: 60, Damage: 20, LootTable: map[string]float64{"shadow_dust": 1.0}},
		},
		RequiredLevel: 10,
		RequiredItem:  "iron_pickaxe",
		Descriptions: []string{
			"The darkness here feels heavy, almost physical.",
			"Faint whispers seem to drift from the bottomless pits nearby.",
			"A glint of something precious catches your light in the deep gloom.",
			"The rock here is unnaturally hard, singing with a low hum when struck.",
		},
	},
	"nether": {
		Name: "🔥 Nether",
		LootTable: map[string]float64{
			"quartz":         0.5,
			"netherite":      0.3,
			"nether_crystal": 0.2,
		},
		EncounterChance: 0.4,
		EncounterTable: []Monster{
			{Name: "🔥 Blaze", Health: 80, Damage: 25, LootTable: map[string]float64{"blaze_rod": 1.0}},
			{Name: "☁️ Ghast", Health: 50, Damage: 40, LootTable: map[string]float64{"ghast_tear": 1.0}},
		},
		RequiredLevel: 25,
		RequiredItem:  "diamond_pickaxe",
		Descriptions: []string{
			"Heat waves distort the air around the bubbling lava lakes.",
			"The ground itself seems to groan under the volcanic pressure.",
			"Cinders fall like glowing snow from the jagged red ceiling.",
			"You chip away at the glowing quartz while shielding your eyes from the glare.",
		},
	},
	"void": {
		Name: "🌌 Void",
		LootTable: map[string]float64{
			"void_essence": 0.5,
			"star_matter":  0.3,
			"void_crystal": 0.2,
		},
		EncounterChance: 0.5,
		EncounterTable: []Monster{
			{Name: "👾 Void Reaver", Health: 150, Damage: 50, LootTable: map[string]float64{"void_core": 1.0}},
		},
		RequiredLevel: 50,
		RequiredItem:  "nether_pickaxe",
		Descriptions: []string{
			"Reality feels thin here, shimmering like oil on water.",
			"There is no sound, only the vibration of the cosmos in your bones.",
			"Stars seem to drift past you in the endless indigo expanse.",
			"You reach into the nothingness and pull back fragments of pure energy.",
		},
	},
}

var Recipes = map[string]Recipe{
	// --- Standard Mining Gear (Mine Loot Only) ---
	"wood_pickaxe": {
		Name: "🪵⛏️ Wood Pickaxe",
		Ingredients: map[string]int{"wood": 10},
		ResultType: "tool", ResultValue: 50, RequiredLevel: 1,
	},
	"stone_pickaxe": {
		Name: "🪨⛏️ Stone Pickaxe",
		Ingredients: map[string]int{"wood": 10, "stone": 20},
		ResultType: "tool", ResultValue: 100, RequiredLevel: 3,
	},
	"iron_pickaxe": {
		Name: "⛓️⛏️ Iron Pickaxe",
		Ingredients: map[string]int{"wood": 5, "iron": 20},
		ResultType: "tool", ResultValue: 250, RequiredLevel: 10,
	},
	"diamond_pickaxe": {
		Name: "💎⛏️ Diamond Pickaxe",
		Ingredients: map[string]int{"iron": 10, "diamond": 5},
		ResultType: "tool", ResultValue: 500, RequiredLevel: 25,
	},
	"abyss_pickaxe": {
		Name: "🌑⛏️ Abyss Pickaxe",
		Ingredients: map[string]int{"diamond": 10, "abyss_crystal": 5},
		ResultType: "tool", ResultValue: 1000, RequiredLevel: 35,
	},
	"nether_pickaxe": {
		Name: "🔥⛏️ Nether Pickaxe",
		Ingredients: map[string]int{"netherite": 10, "nether_crystal": 5},
		ResultType: "tool", ResultValue: 2500, RequiredLevel: 45,
	},
	"void_pickaxe": {
		Name: "🌌⛏️ Void Pickaxe",
		Ingredients: map[string]int{"star_matter": 10, "void_crystal": 5},
		ResultType: "tool", ResultValue: 5000, RequiredLevel: 60,
	},
	"sword": {
		Name: "🗡️ Sword",
		Ingredients: map[string]int{"wood": 2, "stone": 10},
		ResultType: "weapon", ResultValue: 5, RequiredLevel: 1,
	},
	"iron_sword": {
		Name: "⚔️ Iron Sword",
		Ingredients: map[string]int{"wood": 2, "iron": 15},
		ResultType: "weapon", ResultValue: 15, RequiredLevel: 8,
	},
	"diamond_sword": {
		Name: "💎⚔️ Diamond Sword",
		Ingredients: map[string]int{"iron": 5, "diamond": 10},
		ResultType: "weapon", ResultValue: 35, RequiredLevel: 25,
	},
	"abyss_sword": {
		Name: "🌑⚔️ Abyss Sword",
		Ingredients: map[string]int{"diamond": 10, "abyss_crystal": 10},
		ResultType: "weapon", ResultValue: 60, RequiredLevel: 35,
	},
	"nether_sword": {
		Name: "🔥⚔️ Nether Sword",
		Ingredients: map[string]int{"netherite": 20, "nether_crystal": 10},
		ResultType: "weapon", ResultValue: 120, RequiredLevel: 45,
	},
	"void_sword": {
		Name: "🌌⚔️ Void Sword",
		Ingredients: map[string]int{"star_matter": 20, "void_crystal": 10},
		ResultType: "weapon", ResultValue: 250, RequiredLevel: 60,
	},

	// --- Specialized Gate Gear (Hybrid: Mine + Gate Loot) ---

	"d_hunter_blade": {
		Name: "🗡️ Hunter's Blade",
		Ingredients: map[string]int{"iron": 20, "goblin_ear": 5},
		ResultType: "weapon", ResultValue: 50, RequiredLevel: 12,
	},
	"d_wolf_slayer": {
		Name: "🐺 Wolf Slayer Greatsword",
		Ingredients: map[string]int{"diamond": 15, "wolf_fang": 10},
		ResultType: "weapon", ResultValue: 120, RequiredLevel: 25,
	},
	"d_naga_trident": {
		Name: "🔱 Naga Trident",
		Ingredients: map[string]int{"abyss_crystal": 20, "naga_scale": 15},
		ResultType: "weapon", ResultValue: 300, RequiredLevel: 40,
	},
	"d_golem_smasher": {
		Name: "🔨 Golem Smasher",
		Ingredients: map[string]int{"netherite": 25, "core_fragment": 20},
		ResultType: "weapon", ResultValue: 800, RequiredLevel: 60,
	},
	"d_dragon_slayer": {
		Name: "🐲 Dragon Slayer",
		Ingredients: map[string]int{"star_matter": 30, "dragon_heart": 10},
		ResultType: "weapon", ResultValue: 2000, RequiredLevel: 80,
	},
	"d_monarch_sword": {
		Name: "👑 Monarch's Sword",
		Ingredients: map[string]int{"void_crystal": 50, "demon_soul": 5},
		ResultType: "weapon", ResultValue: 5000, RequiredLevel: 100,
	},

	// Consumables
	"bread": {
		Name: "🥖 Bread",
		Ingredients: map[string]int{"wood": 5},
		ResultType: "food", ResultValue: 20, RequiredLevel: 2,
	},
	"health_potion": {
		Name: "🧪 Health Potion",
		Ingredients: map[string]int{"gel": 10, "gold": 5},
		ResultType: "food", ResultValue: 50, RequiredLevel: 5,
	},
	"stamina_potion": {
		Name: "⚡ Stamina Potion",
		Ingredients: map[string]int{"gel": 10, "quartz": 10},
		ResultType: "stamina_food", ResultValue: 30, RequiredLevel: 10,
	},
}

var Structures = map[string]Structure{
	"house": {
		Name: "🏠 House",
		Ingredients: map[string]int{
			"wood":  50,
			"stone": 50,
		},
		RequiredLevel: 5,
		PerkDesc:      "Increases health regeneration (+2 per cycle)",
	},
	"farm": {
		Name: "🌾 Farm",
		Ingredients: map[string]int{
			"wood": 100,
			"gel":  20,
		},
		RequiredLevel: 8,
		PerkDesc:      "Increases stamina regeneration (+5 per cycle)",
	},
	"forge": {
		Name: "⚒️ Forge",
		Ingredients: map[string]int{
			"stone": 200,
			"coal":  50,
			"iron":  20,
		},
		RequiredLevel: 12,
		PerkDesc:      "Increases attack power (+10 attack)",
	},
	"enchanting_table": {
		Name: "🧪 Enchanting Table",
		Ingredients: map[string]int{
			"gold":           50,
			"abyss_crystal": 10,
			"diamond":        5,
		},
		RequiredLevel: 15,
		PerkDesc:      "Arcane Wisdom (+50% XP gain from all sources)",
	},
	"vault": {
		Name: "🏦 Vault",
		Ingredients: map[string]int{
			"iron": 100,
			"gold": 20,
		},
		RequiredLevel: 20,
		PerkDesc:      "Increases max health (+50 HP)",
	},
	"castle": {
		Name: "🏰 Castle",
		Ingredients: map[string]int{
			"stone":   1000,
			"iron":    200,
			"diamond": 50,
		},
		RequiredLevel: 40,
		PerkDesc:      "Global Mastery (+20 attack, +100 HP, +50 Stamina)",
	},
}

var BotSettlements = map[string]BotSettlement{
	"goblin_camp": {
		Name:          "👺 Goblin Camp",
		Level:         5,
		RequiredSword: "sword",
		Defenders: []Monster{
			{Name: "👺 Goblin Warrior", Health: 50, Damage: 10},
			{Name: "👺 Goblin Archer", Health: 30, Damage: 15},
		},
		LootTable:   map[string]int{"wood": 20, "stone": 10, "gold": 5},
		Description: "A small camp of pesky goblins. Easy pickings for a beginner.",
	},
	"bandit_fort": {
		Name:          "🏴‍☠️ Bandit Fort",
		Level:         15,
		RequiredSword: "iron_sword",
		Defenders: []Monster{
			{Name: "🏴‍☠️ Bandit Thug", Health: 100, Damage: 20},
			{Name: "🏴‍☠️ Bandit Leader", Health: 200, Damage: 35},
		},
		LootTable:   map[string]int{"iron": 50, "gold": 25, "diamond": 2},
		Description: "A fortified base filled with ruthless outlaws.",
	},
	"shadow_keep": {
		Name:          "🏰 Shadow Keep",
		Level:         35,
		RequiredSword: "diamond_sword",
		Defenders: []Monster{
			{Name: "👻 Shadow Knight", Health: 300, Damage: 50},
			{Name: "👻 Shadow Mage", Health: 150, Damage: 80},
		},
		LootTable:   map[string]int{"diamond": 20, "netherite": 5, "void_essence": 2},
		Description: "A dark fortress where shadows linger. Extremely dangerous.",
	},
}

var MerchantInventory = map[string]ShopItem{
	"golden_apple": {
		ID:    "golden_apple",
		Name:  "🍎 Golden Apple",
		Price: 50,
		Desc:  "Instantly restores 100 HP.",
	},
	"energy_drink": {
		ID:    "energy_drink",
		Name:  "🥤 Energy Drink",
		Price: 30,
		Desc:  "Instantly restores 50 Stamina.",
	},
	"mystery_box": {
		ID:    "mystery_box",
		Name:  "🎁 Mystery Box",
		Price: 100,
		Desc:  "Contains random high-tier materials.",
	},
	"repair_kit": {
		ID:    "repair_kit",
		Name:  "🔧 Repair Kit",
		Price: 40,
		Desc:  "Fully restores tool durability.",
	},
	"life_stone": {
		ID:    "life_stone",
		Name:  "💎 Life Stone",
		Price: 5000,
		Desc:  "Prevents death penalty once. (Auto-consumes on death)",
	},
}

var GlobalQuests = []Quest{
	{ID: "wood_gatherer", Name: "🌲 Wood Gatherer", TargetType: "item", TargetID: "wood", TargetQty: 50, RewardXP: 100, RewardGold: 20, Description: "Collect 50 Wood from the Surface."},
	{ID: "slime_hunter", Name: "🟢 Slime Hunter", TargetType: "combat", TargetID: "🟢 Slime", TargetQty: 5, RewardXP: 150, RewardGold: 30, Description: "Defeat 5 Slimes on the Surface."},
	{ID: "iron_miner", Name: "⛓️ Iron Miner", TargetType: "item", TargetID: "iron", TargetQty: 30, RewardXP: 300, RewardGold: 100, Description: "Mine 30 Iron from the Caves."},
	{ID: "zombie_slayer", Name: "🧟 Zombie Slayer", TargetType: "combat", TargetID: "🧟 Zombie", TargetQty: 10, RewardXP: 500, RewardGold: 200, Description: "Defeat 10 Zombies in the Caves."},
}

var GateBosses = map[string][]Monster{
	"E": {
		{Name: "👹 Hobgoblin", Health: 100, Damage: 15, LootTable: map[string]float64{"goblin_ear": 1.0}},
		{Name: "🕷️ Small Lesser Taratect", Health: 80, Damage: 10, LootTable: map[string]float64{"string": 1.0}},
	},
	"D": {
		{Name: "🐺 Alpha Wolf", Health: 250, Damage: 30, LootTable: map[string]float64{"wolf_fang": 1.0}},
		{Name: "🕷️ Spider Queen (Small)", Health: 300, Damage: 35, LootTable: map[string]float64{"spider_eye": 0.5, "string": 1.0}},
		{Name: "🌊 Tide Sovereign", Health: 350, Damage: 40, LootTable: map[string]float64{"ocean_gem": 0.5}},
		{Name: "🧟 Lesser Orc Lord", Health: 400, Damage: 45, LootTable: map[string]float64{"orc_meat": 1.0}},
	},
	"C": {
		{Name: "🦎 Naga Warrior", Health: 600, Damage: 60, LootTable: map[string]float64{"naga_scale": 1.0}},
		{Name: "🛡️ Iron Tyrant", Health: 800, Damage: 70, LootTable: map[string]float64{"iron_plate": 0.5}},
		{Name: "💎 Crystal Colossus", Health: 1000, Damage: 80, LootTable: map[string]float64{"crystal_core": 0.5}},
		{Name: "🔥 Flame Ogre", Health: 1200, Damage: 90, LootTable: map[string]float64{"flame_essence": 0.5}},
	},
	"B": {
		{Name: "🦾 Golem Guardian", Health: 1500, Damage: 120, LootTable: map[string]float64{"core_fragment": 1.0}},
		{Name: "🎭 Clayman (Puppeteer)", Health: 2000, Damage: 150, LootTable: map[string]float64{"marionette_string": 0.5}},
		{Name: "💀 Wither King", Health: 2500, Damage: 180, LootTable: map[string]float64{"wither_soul": 0.5}},
		{Name: "🕷️ Greater Taratect", Health: 3000, Damage: 200, LootTable: map[string]float64{"strong_thread": 1.0}},
	},
	"A": {
		{Name: "🔥 Inferno Drake", Health: 4000, Damage: 250, LootTable: map[string]float64{"dragon_heart": 1.0}},
		{Name: "⚔️ Hinata Sakaguchi", Health: 5000, Damage: 300, LootTable: map[string]float64{"holy_sword": 0.1}},
		{Name: "🐲 Earth Dragon Araba", Health: 6000, Damage: 350, LootTable: map[string]float64{"earth_dragon_scale": 0.5}},
		{Name: "🌑 Void Sovereign", Health: 7000, Damage: 400, LootTable: map[string]float64{"void_essence": 0.5}},
	},
	"S": {
		{Name: "👑 Demon King", Health: 10000, Damage: 500, LootTable: map[string]float64{"demon_soul": 1.0}},
		{Name: "👑 Shadow Monarch", Health: 15000, Damage: 600, LootTable: map[string]float64{"monarch_crown": 0.5}},
		{Name: "🦋 Demon Lord Ariel", Health: 20000, Damage: 700, LootTable: map[string]float64{"demon_silk": 0.5}},
	},
	"SS": {
		{Name: "🌌 Void Sovereign (True)", Health: 50000, Damage: 1500, LootTable: map[string]float64{"void_crown": 1.0}},
		{Name: "🌀 Storm Dragon Veldora", Health: 100000, Damage: 2500, LootTable: map[string]float64{"storm_crest": 1.0}},
		{Name: "💖 Demon Lord Milim", Health: 150000, Damage: 3000, LootTable: map[string]float64{"dragon_knuckle": 1.0}},
	},
}

var Gates = map[string]Gate{
	"E": {
		Rank:         "E",
		Floors:       3,
		MinLevel:     5,
		MonsterCount: 5,
		RewardXP:     500,
		RewardGold:   100,
		Descriptions: []string{"A weak magical energy leaks from this small crack in reality.", "The air inside feels slightly heavier than normal."},
	},
	"D": {
		Rank:         "D",
		Floors:       4,
		MinLevel:     15,
		MonsterCount: 8,
		RewardXP:     1500,
		RewardGold:   500,
		Descriptions: []string{"A jagged blue portal pulses with moderate intensity.", "You hear the distant howling of beasts from within."},
	},
	"C": {
		Rank:         "C",
		Floors:       5,
		MinLevel:     30,
		MonsterCount: 12,
		RewardXP:     5000,
		RewardGold:   2000,
		Descriptions: []string{"A swirling green gate looms before you.", "The temperature drops as you approach the entrance."},
	},
	"B": {
		Rank:         "B",
		Floors:       6,
		MinLevel:     50,
		MonsterCount: 15,
		RewardXP:     15000,
		RewardGold:   8000,
		Descriptions: []string{"A massive, stable portal glows with a deep purple hue.", "Ancient symbols etched around the gate glow faintly."},
	},
	"A": {
		Rank:         "A",
		Floors:       8,
		MinLevel:     75,
		MonsterCount: 20,
		RewardXP:     50000,
		RewardGold:   25000,
		Descriptions: []string{"A scorching red gate that seems to melt the ground around it.", "The roar of a dragon echoes from the depths."},
	},
	"S": {
		Rank:         "S",
		Floors:       10,
		MinLevel:     100,
		MonsterCount: 30,
		RewardXP:     200000,
		RewardGold:   100000,
		Descriptions: []string{"A pitch-black gate that absorbs all light.", "The sheer pressure of the energy within makes it hard to breathe."},
	},
	"SS": {
		Rank:         "SS",
		Floors:       12,
		MinLevel:     150,
		MonsterCount: 50,
		RewardXP:     1000000,
		RewardGold:   500000,
		Descriptions: []string{"A shimmering, unstable rift that threatens to tear the world apart.", "You feel the gaze of a god-like being from beyond."},
	},
}

var GlobalTitles = map[string]Title{
	"wolf_slayer": {
		ID:          "wolf_slayer",
		Name:        "🐺 Wolf Slayer",
		KillsNeeded: 50,
		PerkDesc:    "+10 Attack",
		AttackBonus: 10,
	},
	"demon_hunter": {
		ID:          "demon_hunter",
		Name:        "😈 Demon Hunter",
		KillsNeeded: 200,
		PerkDesc:    "+500 Max HP",
		HPBonus:     500,
	},
	"god_slayer": {
		ID:          "god_slayer",
		Name:        "✨ God Slayer",
		KillsNeeded: 1000,
		PerkDesc:    "+100 Attack, +2000 Max HP",
		AttackBonus: 100,
		HPBonus:     2000,
	},
}

var GlobalSkills = map[string]Skill{
	"natures_touch": {
		ID:                "natures_touch",
		Name:              "💚 Nature's Touch",
		DmgBonus:          0,
		Cooldown:          4,
		Desc:              "Heals 20% of max HP.",
		Rank:              "E",
		Type:              "active",
		Category:          "heal",
		Level:             1,
		UnlockRequirement: "Defeat any Gate Boss",
		ReqLevel:          1,
	},
	"power_strike": {
		ID:                "power_strike",
		Name:              "⚔️ Power Strike",
		DmgBonus:          50,
		Cooldown:          3,
		Desc:              "A powerful focused attack dealing 200% weapon damage.",
		Rank:              "E",
		Type:              "active",
		Category:          "attack",
		Level:             2,
		UnlockRequirement: "Defeat any Gate Boss",
		ReqLevel:          1,
	},
	"bone_armor": {
		ID:                "bone_armor",
		Name:              "🦴 Bone Armor",
		DmgBonus:          0,
		Cooldown:          5,
		Desc:              "Creates a shield absorbing 50 damage.",
		Rank:              "E",
		Type:              "active",
		Category:          "defense",
		Level:             1,
		UnlockRequirement: "Defeat any Gate Boss",
		ReqLevel:          1,
	},
	"venom_coat": {
		ID:                "venom_coat",
		Name:              "☠️ Venom Coat",
		DmgBonus:          30,
		Cooldown:          4,
		Desc:              "Coats weapon in venom, dealing damage over time.",
		Rank:              "D",
		Type:              "active",
		Category:          "attack",
		Level:             1,
		UnlockRequirement: "Kill spider queen (0/1)",
		ReqBoss:           "spider queen",
	},
	"tidal_surge": {
		ID:                "tidal_surge",
		Name:              "🌊 Tidal Surge",
		DmgBonus:          80,
		Cooldown:          5,
		Desc:              "A massive wave of water that slams enemies.",
		Rank:              "D",
		Type:              "active",
		Category:          "attack",
		Level:             1,
		UnlockRequirement: "Kill tide sovereign (0/1)",
		ReqBoss:           "tide sovereign",
	},
	"fortify": {
		ID:                "fortify",
		Name:              "🛡️ Fortify",
		DmgBonus:          0,
		Cooldown:          6,
		Desc:              "Temporarily increases defense.",
		Rank:              "C",
		Type:              "active",
		Category:          "defense",
		Level:             1,
		UnlockRequirement: "Kill iron tyrant (0/1)",
		ReqBoss:           "iron tyrant",
	},
	"crystal_shatter": {
		ID:                "crystal_shatter",
		Name:              "💎 Crystal Shatter",
		DmgBonus:          120,
		Cooldown:          5,
		Desc:              "Explodes crystals to deal area damage.",
		Rank:              "C",
		Type:              "active",
		Category:          "attack",
		Level:             1,
		UnlockRequirement: "Kill crystal colossus (0/1)",
		ReqBoss:           "crystal colossus",
	},
	"hellfire": {
		ID:                "hellfire",
		Name:              "🔥 Hellfire",
		DmgBonus:          250,
		Cooldown:          7,
		Desc:              "Summons infernal flames to incinerate foes.",
		Rank:              "B",
		Type:              "active",
		Category:          "attack",
		Level:             1,
		UnlockRequirement: "Kill nether lord (0/1)",
		ReqBoss:           "nether lord",
	},
	"soul_reap": {
		ID:                "soul_reap",
		Name:              "💀 Soul Reap",
		DmgBonus:          300,
		Cooldown:          6,
		Desc:              "Steals the life force of your target.",
		Rank:              "B",
		Type:              "active",
		Category:          "attack",
		Level:             1,
		UnlockRequirement: "Kill wither king (0/1)",
		ReqBoss:           "wither king",
	},
	"void_slash": {
		ID:                "void_slash",
		Name:              "🌑 Void Slash",
		DmgBonus:          500,
		Cooldown:          8,
		Desc:              "A strike that cuts through space itself.",
		Rank:              "A",
		Type:              "active",
		Category:          "attack",
		Level:             1,
		UnlockRequirement: "Kill void sovereign (0/1)",
		ReqBoss:           "void sovereign",
	},
	"dragon_breath": {
		ID:                "dragon_breath",
		Name:              "🐲 Dragon's Breath",
		DmgBonus:          600,
		Cooldown:          10,
		Desc:              "Unleash a torrent of dragon fire.",
		Rank:              "A",
		Type:              "active",
		Category:          "attack",
		Level:             1,
		UnlockRequirement: "Kill ancient dragon (0/1)",
		ReqBoss:           "ancient dragon",
	},
	"arise": {
		ID:                "arise",
		Name:              "👑 Arise",
		DmgBonus:          1000,
		Cooldown:          20,
		Desc:              "Summons defeated enemies as shadow soldiers.",
		Rank:              "S",
		Type:              "active",
		Category:          "attack",
		Level:             1,
		UnlockRequirement: "Kill shadow monarch (0/1)",
		ReqBoss:           "shadow monarch",
	},
	"miners_instinct": {
		ID:                "miners_instinct",
		Name:              "⛏️ Miner's Instinct",
		DmgBonus:          0,
		Cooldown:          0,
		Desc:              "Passive: Increases chance to find rare ores.",
		Rank:              "E",
		Type:              "passive",
		Category:          "utility",
		Level:             1,
		UnlockRequirement: "Achievement: miner_50",
	},
	"thick_skin": {
		ID:                "thick_skin",
		Name:              "🛡️ Thick Skin",
		DmgBonus:          0,
		Cooldown:          3,
		Desc:              "Reduces incoming damage by 50% for this turn.",
		Rank:              "E",
		Type:              "active",
		Category:          "defense",
		Level:             1,
		UnlockRequirement: "Dungeon Level 10",
		ReqLevel:          10,
	},
	"trap_sense": {
		ID:                "trap_sense",
		Name:              "🔍 Trap Sense",
		DmgBonus:          0,
		Cooldown:          0,
		Desc:              "Passive: Decreases damage from dungeon traps.",
		Rank:              "D",
		Type:              "passive",
		Category:          "defense",
		Level:             1,
		UnlockRequirement: "Clear spiders nest (0/5)",
	},
	"critical_eye": {
		ID:                "critical_eye",
		Name:              "👁️ Critical Eye",
		DmgBonus:          0,
		Cooldown:          0,
		Desc:              "Passive: Increases critical hit chance.",
		Rank:              "C",
		Type:              "passive",
		Category:          "attack",
		Level:             1,
		UnlockRequirement: "Clear crystal depths (0/5)",
	},
	"battle_hardened": {
		ID:                "battle_hardened",
		Name:              "💪 Battle Hardened",
		DmgBonus:          0,
		Cooldown:          0,
		Desc:              "Passive: Increases attack power based on missing HP.",
		Rank:              "B",
		Type:              "passive",
		Category:          "attack",
		Level:             1,
		UnlockRequirement: "Dungeon Level 35",
		ReqLevel:          35,
	},
	"eclipse_affinity": {
		ID:                "eclipse_affinity",
		Name:              "🌟 Eclipse Affinity",
		DmgBonus:          0,
		Cooldown:          0,
		Desc:              "Passive: Greatly enhances all dark-attribute skills.",
		Rank:              "S",
		Type:              "passive",
		Category:          "utility",
		Level:             1,
		UnlockRequirement: "Kill shadow monarch (0/3)",
		ReqBoss:           "shadow monarch",
	},
	// --- Anime Slime Path ---
	"predator": {
		ID:                "predator",
		Name:              "🌀 Predator",
		DmgBonus:          100,
		Cooldown:          5,
		MPCost:            20,
		Desc:              "Unique: Executing skill. Absorbs enemies < 20% HP to gain permanent stats.",
		Rank:              "Unique",
		Type:              "active",
		Category:          "attack",
		Level:             1,
		UnlockRequirement: "Slime Origin",
	},
	"great_sage": {
		ID:                "great_sage",
		Name:              "🧠 Great Sage",
		DmgBonus:          0,
		Cooldown:          0,
		MPCost:            0,
		Desc:              "Unique: Passive analysis. Increases Defense and Critical Hit chance.",
		Rank:              "Unique",
		Type:              "passive",
		Category:          "utility",
		Level:             1,
		UnlockRequirement: "Slime Origin",
	},
	"water_blade": {
		ID:                "water_blade",
		Name:              "💧 Water Blade",
		DmgBonus:          150,
		Cooldown:          3,
		MPCost:            10,
		Desc:              "High-pressure water that cuts through anything.",
		Rank:              "B",
		Type:              "active",
		Category:          "attack",
		Level:             1,
		UnlockRequirement: "Slime Origin",
	},
	"black_lightning": {
		ID:                "black_lightning",
		Name:              "⚡ Black Lightning",
		DmgBonus:          400,
		Cooldown:          6,
		MPCost:            50,
		Desc:              "Devastating dark lightning strike.",
		Rank:              "A",
		Type:              "active",
		Category:          "attack",
		Level:             1,
		UnlockRequirement: "Slime Origin",
	},
	"megiddo": {
		ID:                "megiddo",
		Name:              "☀️ Megiddo (God's Wrath)",
		DmgBonus:          2000,
		Cooldown:          15,
		MPCost:            200,
		Desc:              "Ultimate: Condensed sunlight rays. Near-instant death.",
		Rank:              "Ultimate",
		Type:              "active",
		Category:          "attack",
		Level:             1,
		UnlockRequirement: "Evolution: Demon Slime",
	},
	"raphael": {
		ID:                "raphael",
		Name:              "📚 Wisdom King Raphael",
		DmgBonus:          0,
		Cooldown:          0,
		MPCost:            0,
		Desc:              "Ultimate: Evolved Great Sage. Near-perfect evasion and analysis.",
		Rank:              "Ultimate",
		Type:              "passive",
		Category:          "utility",
		Level:             1,
		UnlockRequirement: "Evolution: Demon Slime",
	},
	"beelzebuth": {
		ID:                "beelzebuth",
		Name:              "👹 Gluttonous King Beelzebuth",
		DmgBonus:          500,
		Cooldown:          8,
		MPCost:            100,
		Desc:              "Ultimate: Evolved Predator. Absorbs enemies < 40% HP. Massive stat gain.",
		Rank:              "Ultimate",
		Type:              "active",
		Category:          "attack",
		Level:             1,
		UnlockRequirement: "Evolution: Demon Slime",
	},
	// --- Anime Spider Path ---
	"appraisal": {
		ID:                "appraisal",
		Name:              "👁️ Appraisal",
		DmgBonus:          0,
		Cooldown:          0,
		MPCost:            0,
		Desc:              "Unique: Passive analysis. Reveals exact enemy HP and stats in combat.",
		Rank:              "Unique",
		Type:              "passive",
		Category:          "utility",
		Level:             1,
		UnlockRequirement: "Spider Origin",
	},
	"spider_thread": {
		ID:                "spider_thread",
		Name:              "🕸️ Spider Thread",
		DmgBonus:          0,
		Cooldown:          4,
		MPCost:            5,
		Desc:              "Unique: Restrains enemy, reducing their damage by 50% for 2 turns.",
		Rank:              "Unique",
		Type:              "active",
		Category:          "defense",
		Level:             1,
		UnlockRequirement: "Spider Origin",
	},
	"poison_fang": {
		ID:                "poison_fang",
		Name:              "🐍 Poison Fang",
		DmgBonus:          100,
		Cooldown:          3,
		MPCost:            10,
		Desc:              "Injects lethal venom dealing damage over time.",
		Rank:              "C",
		Type:              "active",
		Category:          "attack",
		Level:             1,
		UnlockRequirement: "Spider Origin",
	},
	"evil_eye": {
		ID:                "evil_eye",
		Name:              "🧿 Evil Eye of Statis",
		DmgBonus:          200,
		Cooldown:          5,
		MPCost:            40,
		Desc:              "Paralyzes the enemy, skipping their next turn.",
		Rank:              "B",
		Type:              "active",
		Category:          "attack",
		Level:             1,
		UnlockRequirement: "Spider Origin",
	},
	"ruler_of_pride": {
		ID:                "ruler_of_pride",
		Name:              "👑 Ruler of Pride",
		DmgBonus:          0,
		Cooldown:          10,
		MPCost:            0,
		Desc:              "Unique: 3x Damage multiplier for 3 turns, but lose 10% HP per turn.",
		Rank:              "Unique",
		Type:              "active",
		Category:          "utility",
		Level:             1,
		UnlockRequirement: "Spider Origin",
	},
	"parallel_minds": {
		ID:                "parallel_minds",
		Name:              "🧠 Parallel Minds",
		DmgBonus:          0,
		Cooldown:          0,
		MPCost:            0,
		Desc:              "Unique: Passive. Attack twice per turn with basic attacks.",
		Rank:              "Unique",
		Type:              "passive",
		Category:          "attack",
		Level:             1,
		UnlockRequirement: "Spider Origin",
	},
	"wisdom": {
		ID:                "wisdom",
		Name:              "🦉 Wisdom King (Sariel System)",
		DmgBonus:          0,
		Cooldown:          0,
		MPCost:            0,
		Desc:              "Ultimate: Evolved Appraisal. Perfectly reveals all info and predicts moves.",
		Rank:              "Ultimate",
		Type:              "passive",
		Category:          "utility",
		Level:             1,
		UnlockRequirement: "Evolution: Arachne",
	},
	"heresy_magic": {
		ID:                "heresy_magic",
		Name:              "🌌 Heresy Magic",
		DmgBonus:          1000,
		Cooldown:          10,
		MPCost:            150,
		Desc:              "Forbidden: Attacks the enemy's soul directly. Bypasses defense.",
		Rank:              "Forbidden",
		Type:              "active",
		Category:          "attack",
		Level:             1,
		UnlockRequirement: "Taboo Level 10",
	},
}

